apiVersion: apps/v1
kind: Deployment
metadata:
  name: dept-deployment
  namespace: developer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dept
  template:
    metadata:
      labels:
        app: dept
    spec:
      containers:
        - name: dept
          image: observabilityacr9425.azurecr.io/deptdemo:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
            # OpenTelemetry vars
            - name: OTEL_SERVICE_NAME
              value: deptdemo
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.observability.svc.cluster.local:4318
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_TRACES_EXPORTER
              value: otlp
      imagePullSecrets:
        - name: acr-secret
